name: CI

on:
  pull_request:
    branches: master
  push:
    branches: 
      - master
      - dev 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest      
      - 
        name: Dockerhub login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build dockerfile
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --file ./Dockerfile \
            --tag wangqiru/mercury-parser-api:dev

